spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://community-user
          predicates:
            - Path=/user/**

        - id: post_route
          uri: lb://community-post
          predicates:
            - Path=/community/post/**

        - id: third_route
          uri: lb://community-third
          predicates:
            - Path=/third/**

        - id: message_route
          uri: lb://community-message
          predicates:
            - Path=/message/**

        - id: search_route
          uri: lb://community-search
          predicates:
            - Path=/search/**